name: Check build files

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-dist:
    uses: necko-actions/reusable-workflows/.github/workflows/check-directory.yml@v1
    with:
      directory: dist
  biome:
    permissions:
      contents: read
    name: Biome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
      - run: biome ci .
        name: Run Biome CI
